drop table bookedLessons;
drop table lesson;
drop table lessonTime;
drop table purchasedLiftPass;
drop table equipManagement;
drop table roomManagement;
drop table equipReservation;
drop table rentalEquip;
drop table rentalEquipRate;
drop table skiStaff;
drop table hotelStaff;
drop table roomReservation;
drop table room;
drop table roomRate;
drop table member;
drop table customer;
drop view staff;
drop view reservations;

commit;
